---
- name: Create directory for CloudWatch Exporter
  file:
    path: /opt/cloudwatch-exporter
    state: directory

- name: Create CloudWatch Exporter configuration file
  copy:
    dest: /opt/cloudwatch-exporter/cloudwatch.yml
    content: |
      region: "{{ lookup('env', 'AWS_REGION') }}"
      metrics:
        - aws_namespace: AWS/ECS
          aws_metric_name: CPUUtilization
          aws_dimensions: [ClusterName, ServiceName]
          period_seconds: 60
          range_seconds: 600
        - aws_namespace: AWS/ECS
          aws_metric_name: MemoryUtilization
          aws_dimensions: [ClusterName, ServiceName]
          period_seconds: 60
          range_seconds: 600

- name: Run CloudWatch Exporter container
  docker_container:
    name: cloudwatch-exporter
    image: quay.io/prometheus/cloudwatch-exporter:latest
    ports:
      - "9106:9106"
    volumes:
      - /opt/cloudwatch-exporter/cloudwatch.yml:/config/config.yml
    env:
      AWS_REGION: "{{ lookup('env', 'AWS_REGION') }}"
    command: "--config.file=/config/config.yml"
    state: started
    restart_policy: always
