---
- targets:
    - 'prometheus.monitoring.local:9100'
    - 'grafana.monitoring.local:9100'
  labels:
    job: 'node_exporter'

- targets:
    - 'prometheus.monitoring.local:9106'
  labels:
    job: 'cw_exporter'

- targets:
    - 'prometheus.monitoring.local:8000'
  labels:
    job: 'ecs-task-counter'